name: Ejecutar mi script de Python

on:
  push:
    branches: [ "main" ]

jobs:
  ejecutar-python:
    runs-on: ubuntu-latest

    steps:
      # 1. Copia tu código desde el repositorio a la máquina virtual
      - name: Descargar repositorio
        uses: actions/checkout@v4

      # 2. Prepara Python en la máquina virtual
      - name: Configurar entorno de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. EJECUTA TU SCRIPT REAL
      - name: Ejecutar script main.py
        run: python main.py
